version: "3.6"
services:
  ae-fork-detection:
    build: .
    container_name: ae-fork-detection
    depends_on:
      - fork-postgres
    ports:
      - 3000:3000
    environment:
      - BOT_TOKEN=
      - CHAT_ID=
      # all optional
      - POSTGRES_PASSWORD=postgres # replace with your own credentials
      - POSTGRES_USER=postgres # replace with your own credentials
      - POSTGRES_DB=mainnet
      - POSTGRES_HOST=fork-postgres
    restart: unless-stopped

  fork-postgres:
    image: postgres
    hostname: fork-postgres
    restart: unless-stopped
    container_name: fork-postgres
    environment:
      - POSTGRES_PASSWORD=postgres # replace with your own credentials
      - POSTGRES_USER=postgres # replace with your own credentials
      - POSTGRES_DB=mainnet
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
